server:
  port: 8099

# Firebase Config - JWT Issuer URI
spring.security.oauth2.resourceserver.jwt.issuer-uri: https://securetoken.google.com/

# PostgreSQL Config
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    show-sql: true
spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: admin
  initialization-mode: always
  initialize: true
  schema: classpath:/schema.sql
  continue-on-error: true

#redis Config
redis-key:
  company-profile2: "Project:Ecommerce"

spring.data.redis:
    host: localhost
    password: 6379
    database: 0
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        # 当池耗尽时，在引发异常之前连接分配可以阻塞的最长时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    # 连接超时时间
    timeout: 10000ms
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    cache:
      type: redis